'use strict';

/*
 * Copyright © 2026 FGx.
 * All rights reserved.
 */

const fs = require('node:fs');
const path = require('node:path');
const { SlashCommandBuilder, EmbedBuilder } = require('discord.js');
const { BRAND } = require('../../config/constants');
const achievementsService = require('../../services/clan/achievementsService');

/**
 * /achievements — visual badge catalog.
 * Each achievement renders as a compact embed with its badge image
 * (assets/achievements/<code>.png, generated by scripts/generateAchievementImages.js).
 */

const ASSET_DIR = path.join(__dirname, '..', '..', 'assets', 'achievements');

function badgePath(code) {
  return path.join(ASSET_DIR, `${code}.png`);
}

module.exports = {
  data: new SlashCommandBuilder()
    .setName('achievements')
    .setDescription('View FGx achievements.')
    .addUserOption((o) => o.setName('user').setDescription('Member (default: you)')),
  async execute(interaction) {
    const target = interaction.options.getUser('user') ?? interaction.user;
    const catalog = achievementsService.catalogFor(interaction.guild.id, target.id);
    const unlockedCount = catalog.filter((a) => a.unlocked).length;

    const files = [];
    const embeds = catalog.map((a) => {
      const filePath = badgePath(a.code);
      const hasImage = fs.existsSync(filePath);
      const embed = new EmbedBuilder()
        .setColor(a.unlocked ? BRAND.colors.primary : BRAND.colors.neutral)
        .setTitle(`${a.unlocked ? a.icon : '🔒'} ${a.name}`)
        .setDescription(a.description)
        .addFields({ name: 'Status', value: a.unlocked ? '✅ Unlocked' : 'Locked', inline: true });
      if (hasImage) {
        files.push({ attachment: filePath, name: `${a.code}.png` });
        embed.setThumbnail(`attachment://${a.code}.png`);
      }
      return embed;
    });

    // Discord allows 10 embeds per message — with 10 badges there is no room
    // for a header embed, so the summary rides on the first badge's footer.
    if (embeds.length <= 9) {
      const header = new EmbedBuilder()
        .setColor(BRAND.colors.primary)
        .setTitle(`Achievements — ${target.username}`)
        .setDescription(
          `${target.username} has unlocked **${unlockedCount}/${catalog.length}** achievements.\n\n` +
            'Badges are earned from recorded competitive results, clan wars, tournaments, and Roblox verification.',
        )
        .setFooter({ text: `${BRAND.footer} • ${interaction.guild.name}` });
      await interaction.reply({ embeds: [header, ...embeds], files });
      return;
    }

    embeds[0].setFooter({
      text: `${BRAND.footer} • ${target.username} has unlocked ${unlockedCount}/${catalog.length} achievements`, 
    });
    await interaction.reply({ embeds, files });
  },
};
