# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=1.0.0
maven_group=com.fgx
archives_base_name=fgx-smp-mod

# Fabric API
fabric_version=0.158.0+26.2

# Java
org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-25.0.4.101-hotspot
